
CREATE TABLE COMPANY
(
  ID      varchar(200) NOT NULL COMMENT 'unique id',
  NAME    varchar(200) NOT NULL COMMENT '이름',
  AGE     INT          NULL COMMENT '나이',
  ADDRESS varchar(200) NULL COMMENT '주소',
  SALARY  INT          NOT NULL COMMENT '급여',
  PRIMARY KEY (ID)
) COMMENT '회사';

CREATE TABLE DEPARTMENT
(
  ID     varchar(200) NOT NULL COMMENT 'unique id',
  DEPT   VARCHAR(200) NOT NULL COMMENT '부서',
  EMP_ID varchar(200) NOT NULL COMMENT 'unique id',
  PRIMARY KEY (ID)
) COMMENT '부서';

ALTER TABLE DEPARTMENT
  ADD CONSTRAINT FK_COMPANY_TO_DEPARTMENT
    FOREIGN KEY (EMP_ID)
    REFERENCES COMPANY (ID);
